cognito_prj/cdu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django_warrant.urls',namespace='dw'))
]

cognito_prj/cognito_prj/urls.py
#from django.contrib.auth import views as auth_views
#from django.urls import re_path

#from .views import ProfileView,UpdateProfileView,MySubsriptions,\
#    AdminListUsers,AdminSubscriptions,LogoutView

app_name ='cognito_prj'


"""cognito_prj URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include(('django_warrant.urls','dw'))),
    path(r'user_info/', TemplateView.as_view(template_name='warrant/user_info.html'), name='user_info'),
    url(r'', LoginView.as_view(), {'template_name': 'warrant/login.html'}, name='login'),
]

cognito_prj/cognito_prj/templates/warrant/admin-list-users.html
{% extends 'warrant/base.html' %}

{% block main_content %}
    <table class="table">
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th></th>
        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.username}}</td>
            <td>{{ obj.first_name }}</td>
            <td>{{ obj.last_name }}</td>
            <td><a href="{% url 'dw:admin-cognito-user' obj.username %}" class="btn btn-success">View</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

cognito_prj/cognito_prj/templates/warrant/admin-subscriptions.html
{% extends 'warrant/base.html' %}

{% block main_content %}
    <h2>Current Subscriptions</h2>
    <table class="table">
        <tr>
            <th>Plan Name</th>
            <th>Description</th>

        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.description }}</td>

        </tr>
    {% endfor %}
    </table>

    <h2>Add User to New Plan</h2>
    <form method='post' class="form">
  {% csrf_token %}
    <table class="table">
        {{ form.errors }}
  {{ form.as_table }}
        </table>
  <input type='submit' value='submit' />
</form>
{% endblock %}

cognito_prj/cognito_prj/templates/warrant/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Cognito Profile{% endblock %}</title>

    {% block css %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% endblock %}

      <style media="all" type="text/css">
          #main-container {
              margin-top:100px;
          }
      </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">{% block nav_title %}Warrant{% endblock %}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'dw:profile' %}">My Profile</a></li>
                            <li><a href="{% url 'dw:update-profile' %}">Update your Profile</a></li>
                            <li><a href="{% url 'dw:subscriptions' %}">My Subscriptions</a></li>
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'dw:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'dw:login' %}">Login</a></li>
                            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

      {% block body %}
        {% block content %}
            <div class="container" id="main-container">
                <div class="row">

                    <div class="col-md-12">
                        {% block main_content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        {% endblock content %}
    {% endblock body %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% block js %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>

cognito_prj/cognito_prj/templates/warrant/login.html
{% extends 'warrant/base.html' %}
{% block title %}Login{% endblock title %}
{% block main_content %}
    <div class="col-md-6">
<form method='post' class="form">
  {% csrf_token %}
    <table class="table">
  {{ form.as_table }}
        </table>
  <input type='submit' value='submit' />
</form>
    </div>
{% endblock %}

cognito_prj/cognito_prj/templates/warrant/logout.html
{% extends 'warrant/base.html' %}
{% block main_content %}
<h1>Logged Out</h1>
{% endblock %}

cognito_prj/cognito_prj/templates/warrant/profile.html
{% extends 'warrant/base.html' %}
{% load cognito_tags %}

{% block main_content %}
    <h1>{{ user|username }}</h1>
    <a href="{% url 'dw:update-profile' %}" class="btn btn-primary">Update your Profile</a>
    <dl>
        <dt>First Name:</dt>
        <dd>{{ user.first_name }}</dd>
        <dt>Last Name:</dt>
        <dd>{{ user.last_name }}</dd>
        <dt>Email:</dt>
        <dd>{{ user.email }}</dd>
        <dt>Address:</dt>
        <dd>{{ user.address }}</dd>
        <dt>Phone:</dt>
        <dd>{{ user.phone_number }}</dd>
        <dt>Gender:</dt>
        <dd>{{ user.gender }}</dd>
        <dt>Preferred Username:</dt>
        <dd>{{ user.preferred_username }}</dd>
        <dt>API Key</dt>
        <dd>{{ user.api_key }}</dd>
        <dt>API Key Id</dt>
        <dd>{{ user.api_key_id }}</dd>
    </dl>
{% endblock main_content %}

cognito_prj/cognito_prj/templates/warrant/subscriptions.html
{% extends 'warrant/base.html' %}

{% block main_content %}

    <table class="table">
        <tr>
            <th>Plan Name</th>
            <th>Description</th>

        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.description }}</td>

        </tr>
    {% endfor %}
    </table>
{% endblock %}

cognito_prj/cognito_prj/templates/warrant/update-profile.html
{% extends 'warrant/base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
    <form action="." method="post" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

cognito_prj/cognito_prj/templates/warrant/user_info.html
{% extends 'warrant/base.html' %}
{% block title %}User Info{% endblock %}
{% block main_content %}
  <p>Username: {{ request.user.username }}</p>
  <p>Email: {{ request.user.email }}</p>
  <p>First Name: {{ request.user.first_name }}</p>
  <p>Last Name: {{ request.user.last_name }}</p>
  <p>ID Token: {{ request.session.ID_TOKEN}}</p>
  <p>Access Token: {{ request.session.ACCESS_TOKEN }}</p>
  <p>Refresh Token: {{ request.session.REFRESH_TOKEN }}</p>
  <p>API Key: {{ request.session.API_KEY }}</p>
  <p>API Key ID: {{ request.session.API_KEY_ID }}</p>
{% endblock %}

cognito_prj/templates/warrant/admin-list-users.html
{% extends 'warrant/base.html' %}

{% block main_content %}
    <table class="table">
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th></th>
        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.username}}</td>
            <td>{{ obj.first_name }}</td>
            <td>{{ obj.last_name }}</td>
            <td><a href="{% url 'dw:admin-cognito-user' obj.username %}" class="btn btn-success">View</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

cognito_prj/templates/warrant/admin-subscriptions.html
{% extends 'warrant/base.html' %}

{% block main_content %}
    <h2>Current Subscriptions</h2>
    <table class="table">
        <tr>
            <th>Plan Name</th>
            <th>Description</th>

        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.description }}</td>

        </tr>
    {% endfor %}
    </table>

    <h2>Add User to New Plan</h2>
    <form method='post' class="form">
  {% csrf_token %}
    <table class="table">
        {{ form.errors }}
  {{ form.as_table }}
        </table>
  <input type='submit' value='submit' />
</form>
{% endblock %}

cognito_prj/templates/warrant/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Cognito Profile{% endblock %}</title>

    {% block css %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% endblock %}

      <style media="all" type="text/css">
          #main-container {
              margin-top:100px;
          }
      </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">{% block nav_title %}Warrant{% endblock %}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'dw:profile' %}">My Profile</a></li>
                            <li><a href="{% url 'dw:update-profile' %}">Update your Profile</a></li>
                            <li><a href="{% url 'dw:subscriptions' %}">My Subscriptions</a></li>
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'dw:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'dw:login' %}">Login</a></li>
                            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

      {% block body %}
        {% block content %}
            <div class="container" id="main-container">
                <div class="row">

                    <div class="col-md-12">
                        {% block main_content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        {% endblock content %}
    {% endblock body %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% block js %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>

cognito_prj/templates/warrant/login.html
{% extends 'warrant/base.html' %}
{% block title %}Login{% endblock title %}
{% block main_content %}
    <div class="col-md-6">
<form method='post' class="form">
  {% csrf_token %}
    <table class="table">
  {{ form.as_table }}
        </table>
  <input type='submit' value='submit' />
</form>
    </div>
{% endblock %}

cognito_prj/templates/warrant/logout.html
{% extends 'warrant/base.html' %}
{% block main_content %}
<h1>Logged Out</h1>
{% endblock %}

cognito_prj/templates/warrant/profile.html
{% extends 'warrant/base.html' %}
{% load cognito_tags %}

{% block main_content %}
    <h1>{{ user|username }}</h1>
    <a href="{% url 'dw:update-profile' %}" class="btn btn-primary">Update your Profile</a>
    <dl>
        <dt>First Name:</dt>
        <dd>{{ user.first_name }}</dd>
        <dt>Last Name:</dt>
        <dd>{{ user.last_name }}</dd>
        <dt>Email:</dt>
        <dd>{{ user.email }}</dd>
        <dt>Address:</dt>
        <dd>{{ user.address }}</dd>
        <dt>Phone:</dt>
        <dd>{{ user.phone_number }}</dd>
        <dt>Gender:</dt>
        <dd>{{ user.gender }}</dd>
        <dt>Preferred Username:</dt>
        <dd>{{ user.preferred_username }}</dd>
        <dt>API Key</dt>
        <dd>{{ user.api_key }}</dd>
        <dt>API Key Id</dt>
        <dd>{{ user.api_key_id }}</dd>
    </dl>
{% endblock main_content %}

cognito_prj/templates/warrant/subscriptions.html
{% extends 'warrant/base.html' %}

{% block main_content %}

    <table class="table">
        <tr>
            <th>Plan Name</th>
            <th>Description</th>

        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.description }}</td>

        </tr>
    {% endfor %}
    </table>
{% endblock %}

cognito_prj/templates/warrant/update-profile.html
{% extends 'warrant/base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
    <form action="." method="post" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

cognito_prj/templates/warrant/user_info.html
{% extends 'warrant/base.html' %}
{% block title %}User Info{% endblock %}
{% block main_content %}
  <p>Username: {{ request.user.username }}</p>
  <p>Email: {{ request.user.email }}</p>
  <p>First Name: {{ request.user.first_name }}</p>
  <p>Last Name: {{ request.user.last_name }}</p>
  <p>ID Token: {{ request.session.ID_TOKEN}}</p>
  <p>Access Token: {{ request.session.ACCESS_TOKEN }}</p>
  <p>Refresh Token: {{ request.session.REFRESH_TOKEN }}</p>
  <p>API Key: {{ request.session.API_KEY }}</p>
  <p>API Key ID: {{ request.session.API_KEY_ID }}</p>
{% endblock %}